import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { useCallback, useState } from 'react';
import Dropzone from 'react-dropzone';
import styled from 'styled-components';
import useMutation from '@/hooks/useMutation';

const inter = Inter({ subsets: ['latin'] });

const StyledDiv = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  height: 200px;
  padding: 20px;
  border: 5px dashed #fff;
  margin: 20px 0;
  cursor: pointer;
`;

const StyledButton = styled.button`
  background: tomato;
  color: #fff;
  text-transform: uppercase;
  padding: 15px 30px;
  border: none;
  border-radius: 5px;
  font-weight: 700;
  cursor: pointer;
`;

const url = '/api/upload-to-aws';

export default function Home() {
  const [image, setImage] = useState(null);
  const { mutate: uploadImage, state } = useMutation({ url });

  const onDrop = useCallback(async (acceptedFiles: any) => {
    const file = acceptedFiles[0];
    setImage(file);
  }, []);

  const handleSubmit = async (e: any) => {
    e.preventDefault();
    if (!image) return;
    const formData = new FormData();
    formData.append('file', image);
    await uploadImage(formData);
    formData.delete('file');
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>Upload Image</h1>
          <StyledDiv>
            <Dropzone onDrop={onDrop}>
              {({ getRootProps, getInputProps }) => (
                <section>
                  <div {...getRootProps()}>
                    <input {...getInputProps()} />
                    <p>Drag & drop some files here, or click to select files</p>
                  </div>
                </section>
              )}
            </Dropzone>
          </StyledDiv>

          <StyledButton onClick={handleSubmit}>Submit</StyledButton>
        </div>
      </main>
    </>
  );
}
